# fly.toml app configuration file generated for live-grants on 2025-01-29T11:44:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'live-grants'
primary_region = 'lhr'
console_command = '/rails/bin/rails console'

[build]

[processes]
  app = './bin/rails server'
  worker = 'bundle exec sidekiq'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
